const panel = document.getElementById("aiAdvisorPanel");
const panelBody = document.getElementById("aiAdvisorBody");
const closeBtn = document.getElementById("aiAdvisorClose");
const panelTitle = document.getElementById("aiAdvisorTitle");
const panelMeta = document.getElementById("aiAdvisorMeta");

let isOpen = false;
let isBusy = false;
let lastRequestId = 0;

function getAiAdvisorUrl() {
  const url = globalThis?.DISASTER_ALERT_FUNCTIONS?.aiAdvisor;
  if (!url) {
    throw new Error("AI advisor function URL is not configured");
  }

  return url;
}

export function openAdvisorPanel() {
  if (!panel) {
    return;
  }

  panel.classList.add("open");
  isOpen = true;
}

export function closeAdvisorPanel() {
  if (!panel) {
    return;
  }

  panel.classList.remove("open");
  isOpen = false;
}

closeBtn?.addEventListener("click", closeAdvisorPanel);

document.addEventListener("keydown", (event) => {
  if (event.key === "Escape" && isOpen) {
    closeAdvisorPanel();
  }
});

function renderLoading(type) {
  if (panelTitle) {
    panelTitle.textContent = "AI Safety Advisor";
  }

  if (panelMeta) {
    panelMeta.textContent = `Analyzing ${type || "disaster"} data...`;
  }

  if (panelBody) {
    panelBody.innerHTML = `
      <div class="ai-advisor-loading">
        <div class="ai-advisor-spinner"></div>
        <div class="ai-advisor-loading-text">
          <span class="ai-typing-dot"></span>
          <span class="ai-typing-dot"></span>
          <span class="ai-typing-dot"></span>
          <span style="margin-left:8px; color:var(--text-muted); font-size:12px;">
            Gemini is analyzing the situation...
          </span>
        </div>
      </div>
    `;
  }
}

function renderError(message) {
  if (panelBody) {
    panelBody.innerHTML = `
      <div class="ai-advisor-error">
        <div class="ai-advisor-error-icon">⚠️</div>
        <div class="ai-advisor-error-text">
          <strong>Unable to Generate Advice</strong>
          <p>${message}</p>
        </div>
      </div>
    `;
  }
}

function severityColor(severity) {
  const norm = String(severity || "moderate").toLowerCase();
  if (norm === "critical") return "var(--critical)";
  if (norm === "high") return "var(--high)";
  if (norm === "moderate") return "var(--moderate)";
  return "var(--low)";
}

function renderAdvice(advice, alertData) {
  const type = alertData.type || "Disaster";
  const severity = String(alertData.severity || alertData.level || "moderate");
  const sevColor = severityColor(severity);

  if (panelTitle) {
    panelTitle.textContent = "AI Safety Advisor";
  }

  if (panelMeta) {
    panelMeta.innerHTML = `
      <span style="color:${sevColor};font-weight:600;">●</span>
      ${type} - ${severity.charAt(0).toUpperCase() + severity.slice(1)} Severity
    `;
  }

  const sections = parseAdviceSections(advice);
  let html = `<div class="ai-advisor-content">`;

  sections.forEach((section, index) => {
    html += `
      <div class="ai-section" style="animation-delay:${index * 0.07}s">
        <div class="ai-section-header">${section.header}</div>
        <div class="ai-section-body">${formatSectionBody(section.body)}</div>
      </div>
    `;
  });

  html += `
    <div class="ai-advisor-footer">
      <div class="ai-footer-badge">
        <span class="ai-gemini-icon">✦</span> Generated by Gemini AI
      </div>
      <div class="ai-footer-disclaimer">
        Advisory is AI-generated. Always follow official emergency services.
      </div>
    </div>
  </div>`;

  if (panelBody) {
    panelBody.innerHTML = html;
  }
}

function parseAdviceSections(text) {
  const sectionRegex = /([🚨🛡️📦📍📞⚠️💡]\s*[A-Z ]+)\n/g;
  const parts = text.split(sectionRegex).filter(Boolean);
  const sections = [];

  for (let i = 0; i < parts.length; i += 1) {
    const trimmed = parts[i].trim();

    if (/^[🚨🛡️📦📍📞⚠️💡]/.test(trimmed) && i + 1 < parts.length) {
      sections.push({
        header: trimmed,
        body: parts[i + 1].trim()
      });
      i += 1;
    } else if (sections.length === 0 && trimmed) {
      sections.push({
        header: "🚨 SITUATION OVERVIEW",
        body: trimmed
      });
    } else if (trimmed && sections.length > 0) {
      sections[sections.length - 1].body += `\n${trimmed}`;
    }
  }

  if (!sections.length) {
    sections.push({
      header: "🛡️ SAFETY ADVISORY",
      body: text
    });
  }

  return sections;
}

function formatSectionBody(text) {
  return text
    .split("\n")
    .map((line) => {
      const trimmed = line.trim();
      if (!trimmed) {
        return "";
      }

      if (/^\d+[\.\)]\s/.test(trimmed)) {
        return `<div class="ai-list-item"><span class="ai-list-num">${trimmed.match(/^\d+/)[0]}</span> ${trimmed.replace(/^\d+[\.\)]\s*/, "")}</div>`;
      }

      if (/^[-•]\s/.test(trimmed)) {
        return `<div class="ai-list-item"><span class="ai-list-bullet">•</span> ${trimmed.replace(/^[-•]\s*/, "")}</div>`;
      }

      return `<p class="ai-text">${trimmed}</p>`;
    })
    .join("");
}

export async function requestAdviceForAlert(alertData) {
  const requestId = ++lastRequestId;

  openAdvisorPanel();
  renderLoading(alertData.type || alertData.disaster || "disaster");
  isBusy = true;

  try {
    const payload = {
      type: alertData.type || "Unknown Disaster",
      severity: alertData.severity || alertData.level || "moderate",
      description: alertData.desc || alertData.description || "",
      lat: alertData.lat,
      lng: alertData.lng
    };

    const response = await fetch(getAiAdvisorUrl(), {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload)
    });

    if (requestId !== lastRequestId) {
      return;
    }

    const data = await response.json().catch(() => ({}));

    if (!response.ok || !data.success) {
      renderError(data.error || "Failed to reach AI service.");
      return;
    }

    renderAdvice(data.advice, alertData);
  } catch (error) {
    if (requestId !== lastRequestId) {
      return;
    }

    console.error("[aiAdvisor]", error);
    renderError("Network error. Check your connection and try again.");
  } finally {
    isBusy = false;
  }
}

export function isAdvisorOpen() {
  return isOpen;
}
